apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: managed-gitops-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - managed
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: env
              operator: In
              values:
                - dev
                - prod
